### ISSUE TITLE
When will extended UI be ported to v7(v139)?

### ISSUE THREAD

**Issue by ghost** [Ferlern/extended-UI#13]
So, when is the port to v7?
The mod is extremely useful but it is kinda sad that I can't use it on v7(v139).

**Comment by Ferlern** [comment]
The mod has been ported to v7. You can find the version for v7 here:
https://github.com/Ferlern/extended-UI-v7 (star it ;D)
or
https://github.com/Ferlern/extended-UI/tree/v7
